Replace math/rand with crypto/rand
microsoft/cluster-api-provider-azurestackhci pull request #206
Opened 2023-03-17 22:02 UTC by ganeshamohana

2023-03-20 19:06 UTC, raghavendra-nataraj requested changes

2023-03-20 19:06 UTC, raghavendra-nataraj commented on pkg/util/util.go
> +		} else {
Can we think of an alternative here. We are not sure when we would hit this

2023-03-20 19:15 UTC, ganeshamohana commented on pkg/util/util.go
> +		} else {
We can propagate the error back to the caller and let them handle it. I can't think of any other ways to handle when we can't generate a random number.

2023-03-23 20:28 UTC, raghavendra-nataraj submitted a review, later dismissed

2023-03-24 18:30 UTC, nwoodmsft commented on pkg/util/util.go
> -	charSet = "abcdefghijklmnopqrstuvwxyz0123456789"
Does this charset limitation/guarantee continue to hold with the switch to moc-pkg rand implementation?

2023-03-24 18:33 UTC, nwoodmsft commented on pkg/util/util.go
> +	return rand.RandomString(n)
If we are reducing this code down to just a wrapper around calling rand.RandomString(n) then it doesn't make a lot of sense to me to keep this RandomAlphaNumericString function. I would remove this function and/or file and just call rand.RandomString(n) directly wherever needed.

2023-03-24 18:44 UTC, ganeshamohana commented on pkg/util/util.go
> -	charSet = "abcdefghijklmnopqrstuvwxyz0123456789"
Yes it'll hold, although moc-pkg might not use the exact same charset for random string generation, it'll guarantee the randomness, alphanumeric and no bad words properties of the string.

2023-03-24 18:44 UTC, ganeshamohana commented on pkg/util/util.go
> +	return rand.RandomString(n)
Thank you for the suggestion, I was on the fence to remove this function but now I'll go ahead and remove this util function.

2023-03-24 18:47 UTC, madhanrm commented on go.mod
> +	github.com/microsoft/wmi v0.5.0-alpha.13 // indirect
This repo shouldnt have dependency with wmi.
can you also bump up github.com/microsoft/moc to remove this dependency.

2023-03-24 18:55 UTC, ganeshamohana commented on go.mod
> +	github.com/microsoft/wmi v0.5.0-alpha.13 // indirect
I think it's because moc-pkg has wmi as dependency and since we're using moc-pkg here, wmi is added as indirect dependency.

2023-03-25 00:46 UTC, nwoodmsft approved these changes

2023-03-28 19:09 UTC, closed without merging